apiVersion: v1
kind: Service
metadata:
  name: minha-api-service
  namespace: default
spec:
  selector:
    app: minha-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort